### ISSUE TITLE
7z not extracting ece391_sp15.zip

### ISSUE THREAD

**Issue by bjackson** [TakefiveInteractive/ece391ForMac#1]
7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=utf8,Utf16=on,HugeFiles=on,8 CPUs)

Processing archive: ece391_sp15.zip

Error: Can not open file as archive

**Comment by Tedko** [comment]
let me check it

Brett Jackson notifications@github.com于2015年8月27日周四 13:34写道：

**Comment by Tedko** [comment]
I got this:

```
7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=utf8,Utf16=on,HugeFiles=on,4 CPUs)

Processing archive: ece391_sp15.zip

Extracting  ece391
Extracting  ece391/image
```

**Comment by Tedko** [comment]
will use tar file instead of .zip soon
