### ISSUE TITLE
GRUB Error

### ISSUE THREAD

**Issue by Tedko** [TakefiveInteractive/ece391ForMac#5]
I can reproduce it.
<img width="832" alt="2015-09-15 4 27 56" src="https://cloud.githubusercontent.com/assets/6687437/9890659/d405d740-5bc6-11e5-9d2e-b37a5ae9cc34.png">

**Comment by Tedko** [comment]
@tengyifei

**Comment by markzyu** [comment]
Try using a different devel.qcow. Maybe yours is corrupted. You should be able to find a backup devel.qcow in the classdir (V:)

**Comment by tengyifei** [comment]
Tried that. Didn’t work.

**Comment by markzyu** [comment]
Does every Mac have this problem? If it's not devel.qcow's problem then we are lucky because his changes are not corrupted. I would check ece391.qcow (the base image) and reinstall qemu if it still does not work.

**Comment by Tedko** [comment]
another student also encounter this on piazza.
I completely redo the whole setup (del the ece391 dir and run ./start
again); the student on piazza fix it by reinstall. but mine is still broken.

C4Phone notifications@github.com于2015年9月16日周三 上午10:35写道：

**Comment by Tedko** [comment]
suspect qemu now

Suji YHWH yanhan02008@gmail.com于2015年9月16日周三 上午11:20写道：

**Comment by Tedko** [comment]
I just reinstall the qemu 1.5 by `make clean;make;sudo make install;` still got GRUB

**Comment by markzyu** [comment]
Did you uninstall and remove all configuration files (which are generated by
qemu not by make and thus will not be overwritten) before make install?

**Comment by Tedko** [comment]
ok.have a try

C4Phone notifications@github.com于2015年9月16日周三 17:25写道：

> Did uninstall and remove all configuration files (which are generated by
> qemu not by make and thus will not be overwritten) before make install?

**Comment by Tedko** [comment]
reinstall qemu; also rm all bin files from /bin , still not working

**Comment by markzyu** [comment]
I should have told you that configuration files are stored in places like
/etc and ~

**Comment by Tedko** [comment]
I found some confg files in /usr/local/etc 
see if it works

**Comment by Tedko** [comment]
not working - -

**Comment by markzyu** [comment]
Sorry that it's still not working... but I guess that's I all know about how to fix a software on a Unix system...

**Comment by Tedko** [comment]
try to install qemu in other dir or something L

**Comment by Tedko** [comment]
Fixed by 95abe9b33a58f90aa5515829fa7057c2821b8554
