### ISSUE TITLE
Tux Controller does not work within QEMU

### ISSUE THREAD

**Issue by tanishq-dubey** [TakefiveInteractive/ece391ForMac#6]
The tux controller does not work within QEMU. OS X can recognize the controller as `/dev/tty.usbserial-ece391' but QEMU does nothing.

**Comment by Tedko** [comment]
@tengyifei 
Actually it works. We wrote a bash file for it.

**Comment by Tedko** [comment]
Seems like you are struggling on an MP. Good luck. I will find the script and make it work asap

**Comment by tanishq-dubey** [comment]
I tried opening the test machine and using the demo input program but nothing is recognized on QEMU. Looking though /dev/ doesn't show a serial device either. However, my Mac does show the device (as stated above) and if I screen the serial port, I can see the buttons being pressed.

**Comment by tanishq-dubey** [comment]
Thanks for trying to find the script. It'd really help with local testing!

**Comment by Tedko** [comment]
we used an socat to solve this,
Here's the bash

``` fish
#!/bin/bash
socat UNIX-LISTEN:/tmp/ece391socket,fork /dev/tty.usbserial-ECE391,raw,echo=0,ispeed=9600,ospeed=9600,clocal=1,cs8,nonblock=1,ixoff=0,ixon=0,crtscts=0


```

**Comment by tengyifei** [comment]
I would recommend doing this particular MP in the lab. We didn't fully automate the process of setting up Tux in OS X yet. You need `socat` among others.

**Comment by tanishq-dubey** [comment]
I definitely plan on doing/testing this MP in the lab, it's just that you can't always be in the lab. Thanks to the both of you!

EDIT: I might suggest adding that code snippet to the readme. Your repo is pretty popular for OS X users in class right now.

**Comment by Tedko** [comment]
@tanishq-dubey let me know if `socat` work. Cannot recall other setups, but this should work in most cases.

**Comment by tengyifei** [comment]
From the back of my head and some last year's records:

Open up the first terminal and launch:

```
socat UNIX-LISTEN:/tmp/ece391socket,fork /dev/tty.usbserial-ECE391,raw,echo=0,ispeed=9600,ospeed=9600,clocal=1,cs8,nonblock=1,ixoff=0,ixon=0,crtscts=0
```

Open up the second terminal, launch qemu with this extra parameter:

```
-serial unix:/tmp/ece391socket
```

Let me know if you have any questions

**Comment by tanishq-dubey** [comment]
Yep that works. Thanks again!

**Comment by Tedko** [comment]
@tanishq-dubey readme is updated (and with the very large donation link :100: )
